services:
  db:
    image: pgvector/pgvector:pg18-trixie
    profiles: ["app", "db"]
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db-data:/var/lib/postgresql

  server:
    build: .
    profiles: ["app"]
    restart: always
    depends_on:
      - db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      SERVER__DATABASE__DATABASE: db
      SERVER__DATABASE__USER: postgres
      SERVER__DATABASE__PASSWORD: password
      SERVER__DATABASE__HOST: db
      SERVER__DATABASE__PORT: "5432"
      SERVER_CONFIG_PATH: /app/config.yml
    volumes:
      - ./server:/app/server
      - ./model:/app/model
      - ./gallery_example:/images
      - ./thumbnails:/thumbnails
      - ./weights:/weights
      - ./dev-config.yml:/app/config.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    profiles: ["app"]
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
