select = ["ALL"]
ignore = [
  "D", # Docstring issues
  "FA102", # Blocks "|" type union operator usage, even though it is valid in Python 3.10+,
  "PLR2004", # Blocks magic values, but checking for dimensions is not 'magic'
  "G004", # Bans f strings from logging, I don't like it.
  "PLR0913", # Functions can have multiple parameters and its fine
  ]

[lint.per-file-ignores]
"**/tests/**" = [
    "S101", # Blocks usage of assert,
    "FBT001",
]
"preprocess_sketchy.py" = [
  "T201", # it's a 'appendix' script, not part of the main codebase
  "C901",
]
