# Training settings
training:
  epochs: 1
  base_lr: 0.01
  batch_size: 128
  optimizer: adam
  fraction_of_samples: 0.25
  sketches_path: "data/sketches/"
  images_path: "data/images/"
  dcl_temperature: 0.7

# Model settings
skitter:
  projection_head_size: 256
  embedding_size: 512
  encoder_name: "convnext_tiny.in12k_ft_in1k"

validation:
  eval_every_steps: 200
  validation_fraction: 0.1