# Training settings
training:
  epochs: 50
  base_lr: 0.0005
  batch_size: 64
  optimizer: adamw
  fraction_of_samples: 0.5
  sketches_path: "data/sketches/"
  images_path: "data/images/"

# Model settings
skitter:
  projection_head_size: 2048
  embedding_size: 512
  encoder_name: "convnext_tiny.in12k_ft_in1k"

validation:
  eval_every_steps: 1000
  validation_fraction: 0.2
